<?php /*?><?=$website_name ?><?php */?>
<?php
/*
 * CONFIG - base tag & minification
 */  
// DEVELOPMENT SERVER
// $cowoserverfolder = 'sync/sites/_carl_github/cowoBoilerplate'; 
$cowoserverfolder = 'sync/dev_github/cowoBoilerplate'; 
if($_SERVER['SERVER_NAME']=='localhost' || $_SERVER['SERVER_NAME']=='cowoserver' || $_SERVER['SERVER_NAME']=='172.16.0.100') {
	$domain = 'localhost'; // for html // 'cowoserver' (NON-IP) doesn't work with devices // 172.16.0.100
	// $path = 'http://'.$domain.'/carljohansson/'; // for php // NOT USED YET ! - for INCLUDES INSIDE INCLUDES THINGEE
	?>         
  <base href="http://<?=$domain ?>/<?=$cowoserverfolder ?>/">
  <?php /* <base href="http://<?php echo "$path"; ?>"> */ ?>    
  <?php
  $min='FALSE';
}
// PRODUCTION SERVER
elseif($_SERVER['SERVER_NAME']=='carljohansson.net' || $_SERVER['SERVER_NAME']=='www.carljohansson.net') {	
	$domain = 'www.carljohansson.net/tools/cowoBoilerplate/';
	// $path = 'www.carljohansson.net';
	?>       
	<base href="http://<?=$domain ?>/">    
	<?php
	// $min='TRUE';
	$min='FALSE'; // vs TRUE (ALL MINIFIED AND CONCATENATED) (falta mejorar el grunt process, pero ya casi estoy ahi)
}
// STAGING SERVER
else
{	
	$domain = '212.34.152.30/~tscjnet';
	// $path = 'www.carljohansson.net';
	?> 
	<base href="http://<?=$domain ?>/">     
	<?php
	$min='FALSE'; // vs TRUE, to test grunt online
}
?>

<?php /*?>
<style>
  body {border: 30px solid red;}
</style>
<?php */?>

<?php 
/*
 * CONFIG - CSS THEME SELECTOR :-) - ASI ME OBLIGO A MAQUETAR MEJOR Y A HACER MEJOR HTML
 */
// $css_theme = 'default'; 
$css_theme = 'theme-02'; 
// $css_theme = 'theme-03'; 
// $css_theme = ''; 
// $css_theme = ''; 
if($css_theme=='default') 
{
?>  

<?php } elseif($css_theme=='theme-02') { ?>   
  <style>
    body {
      --dark-primary-color: #D32F2F;
      --dark-primary-color: #f06; /* this case is just a test, no real velue to it otherwise. */
      --light-primary-color: #FFCDD2;
      --primary-color: #F44336;
      --text-icons: #FFFFFF;
      --accent-color: #CDDC39;
      --accent-color: #f06;
      --primary-text: #212121;
      --secondary-text: #757575;
      --divider-text: #BDBDBD;
      /* first test color shcnem 2, and then other varaiblers */
    }
  </style>
<?php } elseif($css_theme=='theme-03') { ?>      
  <style>
    body {
      /* Palette generated by Material Palette - materialpalette.com/blue/light-green */  
      --dark-primary-color: #1976D2;
      --light-primary-color: #2196F3;
      --primary-color: #BBDEFB;
      --text-icons: #FFFFFF;
      --accent-color: #8BC34A;
      --primary-text: #212121;
      --secondary-text: #757575;
      --divider-text: #BDBDBD;
      /* AAHA MYABE CANAOT SASSIFYTHE VARIABLES IF I WANT TO BEABLE TO CHANGE TEHM, AHH, PORQUESASS LO VPCBIERTE ANUMERO , NO AVARIABEL ... */ 
    }
  </style>
<?php
}
// ELSE - defauklt values comimng fomr the css file
else { ?> 

<?php } ?>




<?php
// DEV SETTINGS:
// 1 - SHOW THE DEV CSS THINGEE
// 2 - SHOS THE DEV GRID THINGEE THAT IS CURRENTLY ISNDIE THE PAGE BASICS INCLUDE 




?>





<?php 
/*
 * CONFIG - LANG (HTML TAG)
 */
// $lang = 'en';  //  no aplicable si llamada esta despues del html tag !!!

/*
 * CONFIG - COPY ETC
 *
 */
$website_name = "cowoBoilerplate";
$website_slogan = "a simple Front-End Boilerplate by <a href='https://twitter.com/carlwebdev' target='_blank'>@carlwebdev</a>";
$website_developer ="<a href='http://cowowo.cat' target='_blank'><img src='assets/img/logos/logo_cowowo.png'></a>";

// WEBSIET - CONTACT DETAILS
// $website_email = "info@company.com";
$website_email = "info@cowowo.cat";
// $website_telephone = "+00 123 456 789"; // vs _tel ...
$website_telephone = "+34 936 672 088"; // vs _tel ...
$website_skype = "skypeuser";

// Cookies Popup/Banner /// Language = Catalan
$copy_popup_cookies = "Aquesta web utilitza 'cookies' propies i de tercers per oferir-te una millor experiència i servei. Al navegar o utilitzar els nostres serveis, acceptes l'ús que fem d'elles.";

// $website_logo ="assets/img/logos/logo-cowoBoilerplate.png";
$website_logo ="assets/img/logos/logo_cowoBoilerplate_white.svg";
// ojo, whiuyte svg logo is a bit smaller than the black png (x4) wtf wahatver ... 

// DEV ASSETS:
$cb_img_random ="https://picsum.photos/1920"; // demo_img_random, demo_img

// CNTACT DETAILS 
// email
// tel
/*
 * CONFIG - COPY - PAGES
 *
 */
$pagename_index = "Home";

$pagename_products = "Products";
$pagename_pricing = "Pricing";
$pagename_services = "Services";
$pagename_news = "News";
$pagename_blog = "Blog";
$pagename_staff = "Staff";
$pagename_testimonials = "Testimonials";
$pagename_faq = "FAQ";

// staff
// testimonials - with quote and rounded thumbnails etc 

$pagename_about = "About Us"; // About & Us
$pagename_contact = "Contact"; // Contact & Us
$pagename_cookies = "Cookies";
$pagename_404 = "404"; // Page Not Found
// & faqs... whatever not, too much shit 
$pagename_legal = "Legal (Notice)"; // Saka Legal Notice, etc




/*
 * COPY
 */
$copy_blog_recent = 'Recent Blog Posts';



$copy_readmore = 'Read More !';





/*
 * CONFIG - ICON FONTS
 */
$icon_navicon='<span data-icon="e" class="icon"></span>';
$icon_search='<span data-icon="f" class="icon"></span>';
$icon_left='<span data-icon="c" class="icon"></span>';
$icon_right='<span data-icon="d" class="icon"></span>';
$icon_up='<span data-icon="b" class="icon"></span>';
$icon_down='<span data-icon="a" class="icon"></span>'; 


/*
 * CONFIG - ICONS / IMAGES
 */
$icon_facebook='<img src="assets/img/icons/social/facebook.png" alt="Facebook">';
$icon_twitter='<img src="assets/img/icons/social/twitter.png" alt="Twitter">';
$icon_linkedin='<img src="assets/img/icons/social/linkedin.png" alt="Linkedin">';
$icon_instagram='<img src="assets/img/icons/social/instagram.png" alt="Instagram">';
$icon_pinterest='<img src="assets/img/icons/social/pinterest.png" alt="Pinterest">';
$icon_googleplus='<img src="assets/img/icons/social/googleplus.png" alt="Google Plus">';
$icon_foursquare='<img src="assets/img/icons/social/foursquare.png" alt="Foursquare">';


/*
 * CONFIG - ICON FONTS / FONT AWESOME
 */
$icon_facebook='<i class="fab fa-facebook-square"></i>';
$icon_twitter='<i class="fab fa-twitter-square"></i>';
$icon_linkedin='<i class="fab fa-linkedin"></i>';
$icon_instagram='<i class="fab fa-instagram-square"></i>';
$icon_pinterest='<i class="fab fa-pinterest-square"></i>';
$icon_googleplus='<i class="fab fa-google-plus-square"></i>';
$icon_foursquare='<i class="fab fa-foursquare"></i>';



/*
 * CONFIG - MATERIAL DESIGN ICONS - https://material.io/
 */
	
$mdi_menu='<span class="material-icons">menu</span>';
$mdi_search='<span class="material-icons">search</span>';
$mdi_email='<span class="material-icons">email</span>';
$mdi_tel='<span class="material-icons">phone_in_talk</span>';

$mdi_aspect_ratio='<span class="material-icons">aspect_ratio</span>';




// HEADER ADMIN SETTINGS & OPTIONS:
// $mdi_settings='<span class="material-icons">settings</span>'; // IS DUPLICATED FURTHER BELOW 
$mdi_style='<span class="material-icons">style</span>'; // WHAT WAS TH EPURPOSE???


$mdi_lightmode='<span class="material-icons">light_mode</span>';
$mdi_darkmode='<span class="material-icons">dark_mode</span>';


$mdi_css='<span class="material-icons">css</span>';
$mdi_debugging='<span class="material-icons">bug_report</span>'; // aka for debugging
$mdi_settings='<span class="material-icons">settings</span>'; // aka for debugging
$mdi_profile='<span class="material-icons">account_circle</span>'; // account_circle VS person

?>


<?php
/*
<?=$icon_facebook ?>
<?php echo $icon_facebook ?>
 */ 
?>

<?php 
// PHP VARIABLES - ICONS (Material Design Icons)
$GLOBALS['icon_link'] ='<span class="material-symbols-outlined">link</span>'; 
$GLOBALS['icon_share'] ='<span class="material-symbols-outlined">share</span>'; 

$GLOBALS['icon_translate'] ='<span class="material-symbols-outlined">translate</span>'; 
$GLOBALS['icon_language'] ='<span class="material-symbols-outlined">language</span>'; 

$GLOBALS['icon_database'] ='<span class="material-symbols-outlined">database</span>'; // CMS VS DATABASE
$GLOBALS['icon_cms'] ='<span class="material-symbols-outlined">database</span>'; // CMS VS DATABASE

$GLOBALS['icon_css'] ='<span class="material-symbols-outlined">css</span>'; // CSS VS STYLE
$GLOBALS['icon_code'] ='<span class="material-symbols-outlined">code</span>'; // CODE VS DEV


$GLOBALS['icon_email'] ='<span class="material-symbols-outlined">email</span>'; // CODE VS DEV



$GLOBALS['icon_menu'] ='<span class="material-symbols-outlined">menu</span>'; 
$GLOBALS['icon_search'] ='<span class="material-symbols-outlined">search</span>'; // <span class="material-icons">search</span>

// $GLOBALS['icon_read_more'] ='<span class="material-symbols-outlined">read_more</span>'; 
// $GLOBALS['icon_read_more'] ='<span class="material-symbols-outlined">arrow_forward_ios</span>'; 
$GLOBALS['icon_read_more'] ='<span class="material-symbols-outlined">east</span>'; 

$GLOBALS['icon_arrow_forward_ios'] ='<span class="material-symbols-outlined">arrow_forward_ios</span>'; // USED IN: .breadcrumbs
// $GLOBALS['icon_arrow_forward_ios'] ='<span class="material-symbols-outlined">arrow_back_ios</span>';

// $GLOBALS['icon_arrow_forward'] ='<span class="material-symbols-outlined">arrow_forward</span>';
// $GLOBALS['icon_east'] ='<span class="material-symbols-outlined">east</span>';
// $GLOBALS['icon_trending_flat'] ='<span class="material-symbols-outlined">trending_flat</span>';

// DARK & LIGHT MODE, AND YSTEM SETTINGGS  COPY FOMR WPIPER.JS WEBSIET 1!!
$GLOBALS['icon_light_mode'] ='<span class="material-symbols-outlined">light_mode</span>'; // icon_sun
$GLOBALS['icon_dark_mode'] ='<span class="material-symbols-outlined">dark_mode</span>'; // icon_moon

// DEV / DEBUGGIN  REAÑTED ICONS - FOR DEBUGGING PURPOSES
/*
$mdi_css='<span class="material-icons">css</span>';
$mdi_debugging='<span class="material-icons">bug_report</span>'; // aka for debugging
$mdi_settings='<span class="material-icons">settings</span>'; // aka for debugging
$mdi_profile='<span class="material-icons">account_circle</span>'; // account_circle VS person
*/

$GLOBALS['icon_css'] ='<span class="material-symbols-outlined">css</span>'; 
$GLOBALS['icon_debugging'] ='<span class="material-symbols-outlined">bug_report</span>'; // aka for debugging
$GLOBALS['icon_settings'] ='<span class="material-symbols-outlined">settings</span>'; // aka for debugging
$GLOBALS['icon_profile'] ='<span class="material-symbols-outlined">account_circle</span>'; // account_circle VS person




$GLOBALS['icon_share'] ='<span class="material-symbols-outlined">share</span>'; // share vs social , share icon is go!
$GLOBALS['icon_cart'] ='<span class="material-symbols-outlined">shopping_cart</span>'; // cart


// BOTH OF THESE ARE INVOED THROUGH SCRIPT, MUCH LIEK THE DARK MODEE TOGGLE DOES IN OTHER SITES, NOT YET IMEMETE HERE IN CB !!!
$GLOBALS['icon_fullscreen'] ='<span class="material-symbols-outlined">fullscreen</span>'; // cart
$GLOBALS['icon_fullscreen_exit'] ='<span class="material-symbols-outlined">close_fullscreen</span>'; // close_fullscreen VS fullscreen_exit 


$GLOBALS['icon_responsive'] ='<span class="material-symbols-outlined">responsive_layout</span>';


$GLOBALS['icon_style'] ='<span class="material-symbols-outlined">style</span>';



?>